SMARC_SAL28_UBOOT_UPDATE_VERSION = 1.0
SMARC_SAL28_UBOOT_UPDATE_SITE = "${BR2_EXTERNAL_SMARC_SAL28_PATH}/package/smarc-sal28-uboot-update/src"
SMARC_SAL28_UBOOT_UPDATE_SITE_METHOD = local
SMARC_SAL28_UBOOT_UPDATE_LICENSE = GPLv2
SMARC_SAL28_UBOOT_UPDATE_LICENSE_FILES = COPYING
SMARC_SAL28_UBOOT_UPDATE_INSTALL_TARGET = NO
SMARC_SAL28_UBOOT_UPDATE_INSTALL_IMAGES = YES

define SMARC_SAL28_UBOOT_UPDATE_INSTALL_IMAGES_CMDS
	cp $(@D)/sl28_uboot_update.its $(BINARIES_DIR)/uboot_update.its
	cp $(@D)/sl28_install.scr $(BINARIES_DIR)/uboot_install.scr
endef

$(eval $(generic-package))
